### ISSUE TITLE
Disabling go metric collection

### ISSUE THREAD

**Issue by martinvelez** [pdf/zfs_exporter#2]
Is there a way to not collect certain metrics, like `go` metrics?

```
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
...
```
I think this is possible in Node Exporter (see https://github.com/prometheus/node_exporter/pull/1148).

**Comment by pdf** [comment]
The Go metrics are included by default on all exporters by the upstream `promhttp` package, which is why you'll see these metrics on nearly all the third-party collectors.  That `node_exporter` PR is a significant refactor, so I'll need to dig into `promhttp` to work out how to avoid exposing them.

This does not seem like a high priority change, so it may take me a little time before I can address it, happy to review a PR though.

**Comment by pdf** [comment]
I've reported this upstream, since it seems to me that incorporating this behaviour there would be a win for all exporters, we'll see what the concensus is:

https://github.com/prometheus/client_golang/issues/884
