### ISSUE TITLE
Can we have more dataset properties?

### ISSUE THREAD

**Issue by riyad** [pdf/zfs_exporter#7]
I was hoping there's a way to add more dataset properties when scraping. Especially `compressratio`,`usedby*` and `snapshot_count` would be of value to me.

Mucking about in the code I was hoping to get to something like this:
```go
type datasetCollector struct {
	kind string
	// all datasets
	compressionRatio       desc
	logicalReferencedBytes desc
	logicalUsedBytes       desc
	usedBytes              desc
	refCompressionRatio    desc
	referencedBytes        desc
	writtenBytes           desc
	// volumes only
	volumeSizeBytes desc
	// filesystems only
	quotaBytes desc
	// volumes and filesystems only (i.e. no snapshots)
	availableBytes            desc
	usedByChildrenBytes       desc
	usedByDatasetBytes        desc
	usedByRefReservationBytes desc
	usedBySnapshotsBytes      desc
	snapshotCount             desc
}
```

I'm not fluent in Go so I'm unfamiliar/slow to understand certain things: is it correct that the [ZFS library used](https://github.com/mistifyio/go-zfs) has the current set of properties hard-coded? o.O  ... with no way of extending the list of properties? :cry: 
I'm assuming this from `dsPropListOptions` in https://github.com/mistifyio/go-zfs/blob/d3ead99562a85f25248b082c86644ef61e6798f0/utils.go#L287 looking like it's "private" and "static".

**Comment by pdf** [comment]
Indeed, the upstream library only supports a subset of available properties. The relevent structure is:
https://github.com/mistifyio/go-zfs/blob/d3ead99562a85f25248b082c86644ef61e6798f0/zfs.go#L25

And the relevant arguments passed to the CLI (based on platform) are:
https://github.com/mistifyio/go-zfs/blob/f784269be439d704d3dfa1906f45dd848fed2beb/utils_notsolaris.go#L10
https://github.com/mistifyio/go-zfs/blob/f784269be439d704d3dfa1906f45dd848fed2beb/utils_solaris.go#L10

It doesn't look like that library is particularly well maintained any more (a lot of outstanding PRs, and no commits in the last 2 years). I may try to find some time to evaluate alternative libraries, however I'd prefer to remain using a library that raps the CLI, and avoid any library that uses CGo bindings against libzfs, due to compatibility concerns. When I initially wrote this code, mistifyio/go-zfs was the most widely used library of that kind, and it looks like that's still the case, in spite of its shortcomings.

**Comment by riyad** [comment]
My preliminary survey seems to indicate that [mystifyio/go-zfs](https://github.com/mystifyio/go-zfs) is still the most popular library. *sigh*
* Most projects are old (i.e. last updated in 2018 or even 2016).
* Big projects tend to have their own CLI wrappers (e.g. [zrepl](https://github.com/zrepl/zrepl) or [LXD](https://github.com/lxc/lxd)).
* Some projects look like they just copy and pasted the relevant code from mystifyio/go-zfs and adapted it to their needs: e.g. https://github.com/maireanu/zfsbeat/blob/master/beater/zfs.go

There seem to be only two more or less maintained projects:
* https://github.com/bicomsystems/go-libzfs (more maintained; used by some Ubuntu projects: e.g. [Zsys](https://github.com/ubuntu/zsys))
* https://github.com/lorenz/go-zfs (less maintained)

If I understand correctly both use C bindings ... one to libzfs-core and the other to the ioctls directly.

**Comment by riyad** [comment]
I'd suggest copy-paste-adapt as a first step and then maybe look into one of the other libraries (I'm currently favoring https://github.com/bicomsystems/go-libzfs). IIRC libzfs-core is a limited API subset that's explicitely kept (binary) compatible by OpenZFS.

FWIW: I was using a tool that linked to it. Building it on a recent Ubuntu allowed me to run it also on the latest LTS (but not the other way round).

**Comment by pdf** [comment]
I'm concerned that relying on libzfs will result in a build matrix explosion whenever there's an ABI breakage - my goal is to build once per platform/arch and have it run there without issue (within reason). The latter library you linked is a non-starter, as it's Linux-specific. I am also concerned about an increase in support requests, due to it not running on one system or another. Your anecdote about forward compatibility issues for another tool linked against libzfs confirms my concerns.

I think if I was to take this on, I'd be inclined to write wrapping/parsing code for the CLI locally, and leave it at that. Doing so would allow some additional flexibility, putting control in the hands of users over which properties for various types are collected (though I'd have to pre-populate all the available attribute data types for the metric output, or perhaps look at some sort of code generation to handle this). However, I have other priorities currently, and don't expect to have time to tackle this in the near future.

**Comment by riyad** [comment]
Hmm, I understand your concern ... seems fair.

**Comment by riyad** [comment]
If you're ok with it I'd like to attempt to integrate the mistifyio/go-zfs code.
I've got a prototype of the integrated and extended properties code already working. I'll try to polish it and break it into smaller PRs: starting with #8. :wink:
Bear in mind that I'm a Go beginner so my approaches/style might look a bit quirky for someone more experienced. :sweat_smile:

**Comment by pdf** [comment]
Please take v2.0.0 for a spin - I've added most of the numeric properties, and the collected properties are now available to be configured per-collector via command-line flags on the exporter (it defaults to the properties that used to be available).

If you find that there are any properties that are still unsupported, I'd welcome a PR for them ;-)

**Comment by riyad** [comment]
Awesome! :smile: I like your improvements. Especially properly mapping ZFS properties to Prometheus metrics (with well defined transformation functions) ... much less tedious and error prone ... and the configuration from CLI is just icing on the cake.

Ooohh ... and it seems the "async/parallel property collection" also made it in. :clap:
